"""
Django settings for nohands_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

import os

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-p8q%n4$u1&g0f(g(f%np4w$)^+-uyd$-d5$nswng)n6@41_8*v')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Django's built-in ALLOWED_HOSTS from environment variable
# Our DynamicAllowedHostsMiddleware handles additional host validation
# based on database state (allowing any host during initial setup)
_ENV_ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if os.environ.get('DJANGO_ALLOWED_HOSTS') else []

# We always include '*' to let Django pass through requests
# Our DynamicAllowedHostsMiddleware does the actual validation
# combining both database hosts and _ENV_ALLOWED_HOSTS
ALLOWED_HOSTS = ['*']

# Store the env-configured hosts separately for use in middleware
DJANGO_ALLOWED_HOSTS_FROM_ENV = [h.strip() for h in _ENV_ALLOWED_HOSTS if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    'rest_framework',
    'projects',  # Must come before allauth to override templates
    'builds',
    'api',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
]

SITE_ID = 1

MIDDLEWARE = [
    'nohands_project.middleware.DynamicAllowedHostsMiddleware',  # Must be first to validate hosts early
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'nohands_project.middleware.SocialAppErrorMiddleware',
    'nohands_project.middleware.InitialSetupMiddleware',
    'nohands_project.cleanup_cookies_middleware.CleanupOldCookiesMiddleware',  # Nettoie les anciens cookies
]

ROOT_URLCONF = 'nohands_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nohands_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# NoHands specific settings
import os

# Directory for temporary Git checkouts
GIT_CHECKOUT_DIR = BASE_DIR / 'tmp' / 'git_checkouts'

# Docker registry settings (can be overridden via environment variables)
DOCKER_REGISTRY = os.environ.get('DOCKER_REGISTRY', '')
DOCKER_REGISTRY_USERNAME = os.environ.get('DOCKER_REGISTRY_USERNAME', '')
DOCKER_REGISTRY_PASSWORD = os.environ.get('DOCKER_REGISTRY_PASSWORD', '')

# Max number of concurrent builds
MAX_CONCURRENT_BUILDS = int(os.environ.get('MAX_CONCURRENT_BUILDS', '1'))

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth settings
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_EMAIL_REQUIRED = False
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/github/login/'
LOGOUT_REDIRECT_URL = '/'

# GitHub OAuth settings
# Note: GitHub OAuth credentials must be configured using the setup_github_oauth management command
# or via the Django admin panel. See GITHUB_OAUTH.md for instructions.
SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'SCOPE': [
            'user',
            'repo',
        ],
        'TOKEN_STRATEGY': 'allauth.socialaccount.providers.oauth2.client.STORE',
    }
}

# Store OAuth tokens so we can use them to access GitHub API
SOCIALACCOUNT_STORE_TOKENS = True

# Session cookie configuration
# Use a custom session cookie name to avoid conflicts with proxied applications
SESSION_COOKIE_NAME = 'nohands_sessionid'
# Also customize CSRF cookie name for consistency
CSRF_COOKIE_NAME = 'nohands_csrftoken'
