# Generated by Django 5.2.8 on 2025-11-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('branch_name', models.CharField(help_text='Branch name at build time', max_length=255)),
                ('image_tag', models.CharField(blank=True, help_text='Generated Docker image tag', max_length=255)),
                ('logs', models.TextField(blank=True, help_text='Build logs')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('push_to_registry', models.BooleanField(default=False, help_text='Whether to push image to registry')),
                ('deploy_after_build', models.BooleanField(default=False, help_text='Whether to deploy after successful build')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='projects.commit')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='projects.gitrepository')),
            ],
            options={
                'verbose_name': 'Build',
                'verbose_name_plural': 'Builds',
                'ordering': ['-created_at'],
            },
        ),
    ]
