# Generated by Django 5.2.8 on 2025-11-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='container_id',
            field=models.CharField(blank=True, help_text='Docker container ID when running', max_length=64),
        ),
        migrations.AddField(
            model_name='build',
            name='container_port',
            field=models.IntegerField(default=8080, help_text='Port to expose from the container'),
        ),
        migrations.AddField(
            model_name='build',
            name='container_status',
            field=models.CharField(choices=[('none', 'Not Started'), ('starting', 'Starting'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='build',
            name='host_port',
            field=models.IntegerField(blank=True, help_text='Host port mapped to container port', null=True),
        ),
    ]
