# Generated by Django 5.2.8 on 2025-11-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_build_container_id_build_container_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='dockerfile_content',
            field=models.TextField(blank=True, default='# Auto-generated Dockerfile\nFROM python:3.11-slim\n\nWORKDIR /app\n\n# Copy requirements first for better caching\nCOPY requirements.txt* ./\nRUN pip install --no-cache-dir -r requirements.txt || true\n\n# Copy application code\nCOPY . .\n\n# Expose the application port\nEXPOSE 8080\n\n# Default command (customize as needed)\nCMD ["python", "-m", "http.server", "8080"]\n', help_text='Custom Dockerfile content'),
        ),
        migrations.AddField(
            model_name='build',
            name='dockerfile_path',
            field=models.CharField(blank=True, default='Dockerfile', help_text='Path to Dockerfile in repository', max_length=255),
        ),
        migrations.AddField(
            model_name='build',
            name='dockerfile_source',
            field=models.CharField(choices=[('generated', 'Auto-generated'), ('custom', 'Custom Content'), ('repo_file', 'File from Repository')], default='generated', help_text='Source of the Dockerfile', max_length=20),
        ),
    ]
