# Generated by Django 5.2.8 on 2025-11-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_add_dockerfile_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='env_content',
            field=models.TextField(blank=True, default='', help_text='Environment variables content (.env file)'),
        ),
    ]
