# Generated by Django 5.2.8 on 2025-11-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Repository name', max_length=255, unique=True)),
                ('url', models.CharField(help_text='Git repository URL or local path', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Repository description')),
                ('default_branch', models.CharField(default='main', help_text='Default branch name', max_length=100)),
                ('dockerfile_path', models.CharField(default='Dockerfile', help_text='Path to Dockerfile in repo', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this repository is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Git Repository',
                'verbose_name_plural': 'Git Repositories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Branch name', max_length=255)),
                ('commit_sha', models.CharField(help_text='Latest commit SHA on this branch', max_length=40)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='projects.gitrepository')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
                'unique_together': {('repository', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(help_text='Commit SHA', max_length=40)),
                ('message', models.TextField(help_text='Commit message')),
                ('author', models.CharField(help_text='Commit author', max_length=255)),
                ('author_email', models.EmailField(help_text='Author email', max_length=254)),
                ('committed_at', models.DateTimeField(help_text='Commit timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='projects.branch')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='projects.gitrepository')),
            ],
            options={
                'verbose_name': 'Commit',
                'verbose_name_plural': 'Commits',
                'ordering': ['-committed_at'],
                'unique_together': {('repository', 'sha')},
            },
        ),
    ]
