# Generated by Django 5.2.8 on 2025-11-22 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='github_id',
            field=models.CharField(blank=True, help_text='GitHub repository ID', max_length=100),
        ),
        migrations.AddField(
            model_name='gitrepository',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who connected this repository', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL),
        ),
    ]
