# Generated by Django 5.2.8 on 2025-11-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_gitrepository_github_id_gitrepository_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_url', models.URLField(blank=True, help_text='Base URL of the application (e.g., http://localhost:8000)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Configuration',
                'verbose_name_plural': 'Application Configuration',
            },
        ),
    ]
