# Generated by Django 5.2.8 on 2025-11-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_app_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text="Hostname or domain (e.g., 'localhost:8000', 'myapp.example.com')", max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this host is currently allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Allowed Host',
                'verbose_name_plural': 'Allowed Hosts',
                'ordering': ['hostname'],
            },
        ),
    ]
